/**
 * SmugMugProvider
 *
 * Photo storage provider that integrates with SmugMug for external hosting.
 * SmugMug handles storage, CDN delivery, and thumbnail generation.
 *
 * ## Status: STUB
 * This is an interface-only implementation. Methods throw NotImplementedError.
 *
 * ## Future Implementation Notes
 * - SmugMug API: https://api.smugmug.com/api/v2
 * - Photos are stored in SmugMug galleries (one per event)
 * - ClubOS stores SmugMug image keys, not URLs
 * - Thumbnails are generated by SmugMug (various sizes available)
 * - Authentication handled separately (OAuth 1.0a)
 *
 * ## SmugMug URL Patterns
 * - Original: https://photos.smugmug.com/.../{ImageKey}_O.jpg
 * - Thumbnail: https://photos.smugmug.com/.../{ImageKey}_{SizeCode}.jpg
 *   - Size codes: Th (tiny), S (small), M (medium), L (large), XL, etc.
 */

import {
  PhotoStorageProvider,
  type ListPhotosOptions,
  type ListPhotosResult,
  type ThumbnailSize,
  NotImplementedError,
} from './PhotoStorageProvider';

/**
 * Configuration for SmugMugProvider
 *
 * Note: API credentials are NOT stored here. Authentication is handled
 * at the application level, not within the provider.
 */
export interface SmugMugProviderConfig {
  /** SmugMug username or nickname */
  nickname: string;

  /** Base folder/category for ClubOS photos */
  baseFolderUri?: string;
}

/**
 * Map ClubOS thumbnail sizes to SmugMug size codes
 * Used in future implementation of getThumbnailUrl
 */
const _SMUGMUG_SIZE_CODES: Record<ThumbnailSize, string> = {
  small: 'S',   // 400px longest edge
  medium: 'M',  // 600px longest edge
  large: 'L',   // 800px longest edge
};

/**
 * SmugMug photo storage provider
 *
 * Leverages SmugMug's photo hosting infrastructure for storage,
 * CDN delivery, and automatic thumbnail generation.
 *
 * ## Authentication
 * SmugMug uses OAuth 1.0a. This provider does NOT handle authentication.
 * Credentials and tokens must be configured at the application level.
 */
export class SmugMugProvider implements PhotoStorageProvider {
  readonly name = 'SmugMugProvider';

  private config: SmugMugProviderConfig;

  constructor(config: SmugMugProviderConfig) {
    this.config = config;
  }

  /**
   * Get the SmugMug URL for the original photo
   * @throws NotImplementedError - Stub implementation
   */
  async getOriginalUrl(_photoId: string): Promise<string> {
    // Future: Fetch image details from SmugMug API
    // Return ArchivedUri or LargestImageUrl
    throw new NotImplementedError('getOriginalUrl', this.name);
  }

  /**
   * Get the SmugMug URL for a thumbnail
   * @throws NotImplementedError - Stub implementation
   */
  async getThumbnailUrl(_photoId: string, _size: ThumbnailSize): Promise<string> {
    // Future: Construct URL using _SMUGMUG_SIZE_CODES[_size]
    throw new NotImplementedError('getThumbnailUrl', this.name);
  }

  /**
   * List photos in a SmugMug gallery (by event)
   * @throws NotImplementedError - Stub implementation
   */
  async listPhotosByEvent(_options: ListPhotosOptions): Promise<ListPhotosResult> {
    // Future: GET /api/v2/album/{albumId}!images
    // Map ClubOS eventId to SmugMug albumId
    throw new NotImplementedError('listPhotosByEvent', this.name);
  }

  /**
   * Delete a photo from SmugMug
   * @throws NotImplementedError - Stub implementation
   */
  async deletePhoto(_photoId: string): Promise<void> {
    // Future: DELETE /api/v2/image/{imageId}
    throw new NotImplementedError('deletePhoto', this.name);
  }

  /**
   * Check SmugMug API connectivity
   * @throws NotImplementedError - Stub implementation
   */
  async healthCheck(): Promise<boolean> {
    // Future: GET /api/v2!authuser to verify credentials
    throw new NotImplementedError('healthCheck', this.name);
  }
}
